[pytest]
DJANGO_SETTINGS_MODULE = funchinese.settings_test
python_files = test_*.py
python_functions = test_*
testpaths = courseApp practiceApp userApp homeApp textbookApp vocabularyAPP
addopts = -ra --tb=short --color=yes
