# Generated by Django 6.0.7 on 2026-07-23 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='副标题')),
                ('cover_image', models.ImageField(blank=True, upload_to='course/covers/', verbose_name='封面图片')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('difficulty', models.CharField(choices=[('beginner', '入门'), ('elementary', '初级'), ('intermediate', '中级'), ('upper_intermediate', '中高级'), ('advanced', '高级')], default='beginner', max_length=20, verbose_name='难度等级')),
                ('heat', models.IntegerField(default=0, verbose_name='热度/学习人数')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('is_free', models.BooleanField(default=True, verbose_name='是否免费')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='原价')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('total_chapters', models.IntegerField(default=0, verbose_name='章节总数')),
                ('total_lessons', models.IntegerField(default=0, verbose_name='课时总数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='章节名称')),
                ('description', models.TextField(blank=True, verbose_name='章节描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courseApp.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'ordering': ['course', 'sort_order', 'id'],
                'unique_together': {('course', 'sort_order')},
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courseApp.coursecategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courseApp.coursecategory', verbose_name='课程分类'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='课时名称')),
                ('description', models.TextField(blank=True, verbose_name='课时描述')),
                ('duration', models.IntegerField(default=0, help_text='预计学习时长（分钟）', verbose_name='预计时长')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_trial', models.BooleanField(default=False, verbose_name='是否可试学')),
                ('video_url', models.URLField(blank=True, verbose_name='视频URL')),
                ('audio_url', models.URLField(blank=True, verbose_name='音频URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courseApp.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '课时',
                'verbose_name_plural': '课时',
                'ordering': ['chapter', 'sort_order', 'id'],
                'unique_together': {('chapter', 'sort_order')},
            },
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', '课文'), ('vocabulary', '生词'), ('sentence', '句型'), ('grammar', '语法'), ('dialogue', '对话'), ('exercise', '练习'), ('pronunciation', '发音'), ('culture', '文化拓展')], max_length=20, verbose_name='内容类型')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='内容标题')),
                ('content', models.JSONField(default=dict, verbose_name='内容数据')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courseApp.lesson', verbose_name='所属课时')),
            ],
            options={
                'verbose_name': '学习内容',
                'verbose_name_plural': '学习内容',
                'ordering': ['lesson', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='学习进度（%）')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courseApp.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户课程报名',
                'verbose_name_plural': '用户课程报名',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('last_studied_at', models.DateTimeField(auto_now=True, verbose_name='最后学习时间')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='尝试次数')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courseApp.lesson', verbose_name='课时')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课时学习进度',
                'verbose_name_plural': '课时学习进度',
                'ordering': ['-last_studied_at'],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
