# Generated by Django 6.0.7 on 2026-07-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('typing', '打字练习'), ('speaking', '口语练习'), ('translate', '英译中'), ('listening', '听力')], max_length=20, verbose_name='练习模式')),
                ('question', models.TextField(verbose_name='题目内容（JSON格式）')),
                ('answer', models.TextField(verbose_name='正确答案')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='选项列表（听力模式）')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courseApp.lesson', verbose_name='所属课时')),
            ],
            options={
                'verbose_name': '练习题',
                'verbose_name_plural': '练习题',
                'ordering': ['lesson', 'question_type', 'sort_order'],
            },
        ),
    ]
