# Generated by Django 6.0.7 on 2026-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='audio_url',
            field=models.URLField(blank=True, verbose_name='音频URL'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='grammar_hint',
            field=models.TextField(blank=True, verbose_name='语法提示'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_images/', verbose_name='句子配图'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='word_analysis',
            field=models.JSONField(blank=True, default=list, verbose_name='逐词分析'),
        ),
    ]
