# Generated by Django 6.0.7 on 2026-07-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0003_exercise_audio_url_exercise_grammar_hint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='词语')),
                ('pinyin', models.CharField(blank=True, max_length=100, verbose_name='拼音')),
                ('pos', models.CharField(blank=True, max_length=50, verbose_name='词性')),
                ('grammar', models.CharField(blank=True, max_length=50, verbose_name='语法成分')),
                ('meaning', models.CharField(blank=True, max_length=100, verbose_name='释义')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='courseApp.exercise', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '逐词分析',
                'verbose_name_plural': '逐词分析',
                'ordering': ['exercise', 'sort_order'],
            },
        ),
    ]
