# Generated by Django 6.0.7 on 2026-07-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0004_wordanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordAnalysis',
        ),
    ]
