# Generated by Django 6.0.7 on 2026-07-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0005_delete_wordanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='options',
        ),
    ]
