# Generated by Django 6.0.7 on 2026-07-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0006_remove_exercise_answer_remove_exercise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['lesson', 'sort_order'], 'verbose_name': '练习题', 'verbose_name_plural': '练习题'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question_type',
        ),
    ]
