# Generated by Django 6.0.7 on 2026-07-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0007_alter_exercise_options_remove_exercise_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='question',
            new_name='sentences',
        ),
    ]
