# Generated by Django 6.0.7 on 2026-07-26 10:58

from django.db import migrations


def migrate_meaning_to_english(apps, schema_editor):
    Exercise = apps.get_model('courseApp', 'Exercise')
    for ex in Exercise.objects.iterator():
        if not ex.word_analysis:
            continue
        changed = False
        new_analysis = []
        for item in ex.word_analysis:
            if 'meaning' in item:
                item['english'] = item.pop('meaning')
                changed = True
            new_analysis.append(item)
        if changed:
            ex.word_analysis = new_analysis
            ex.save(update_fields=['word_analysis'])


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0008_rename_question_exercise_sentences'),
    ]

    operations = [
        migrations.RunPython(migrate_meaning_to_english),
    ]
