# Generated by Django 6.0.7 on 2026-07-23 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('typing', '打字练习'), ('speaking', '口语练习'), ('translate', '英译中模式'), ('listening', '听力模式')], max_length=20, verbose_name='练习模式')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成')], default='in_progress', max_length=20, verbose_name='会话状态')),
                ('total_questions', models.IntegerField(default=0, verbose_name='总题数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确数')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='错误数')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('exercise_snapshot', models.JSONField(blank=True, default=list, verbose_name='题目快照')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='courseApp.lesson', verbose_name='关联课时')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习会话',
                'verbose_name_plural': '练习会话',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField(default=0, verbose_name='题号')),
                ('question_data', models.JSONField(default=dict, verbose_name='题目数据')),
                ('user_answer', models.TextField(blank=True, verbose_name='用户答案')),
                ('correct_answer', models.TextField(blank=True, verbose_name='正确答案')),
                ('is_correct', models.BooleanField(null=True, verbose_name='是否正确')),
                ('score', models.IntegerField(default=0, verbose_name='本题得分')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='practiceApp.practicesession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
                'ordering': ['session', 'question_index'],
            },
        ),
    ]
