"""
Django settings for funchinese project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 从项目根 .env 加载敏感配置（SECRET_KEY / 数据库密码 / 第三方 API Key 等）
load_dotenv(BASE_DIR / '.env')


def get_env(key, default=''):
    """读取环境变量；未设置时返回 default。"""
    return os.environ.get(key, default)


def warn_missing(key):
    """关键配置缺失时给出明确提示，避免静默失效。"""
    import warnings
    warnings.warn(
        '未检测到配置项 %s，请在项目根 .env 中配置（参考 .env.example）。' % key,
        RuntimeWarning,
        stacklevel=2,
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('SECRET_KEY', 'django-insecure-dev-only-placeholder')
if not SECRET_KEY or 'dev-only-placeholder' in SECRET_KEY:
    warn_missing('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    # 'simpleui',  # 安装后台管理皮肤
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    # 加载静态资源必备
    'homeApp',                       # 添加主页应用
    'courseApp',                     # 添加课程应用
    'textbookApp',                   # 添加教材应用
    'vocabularyAPP',                 # 添加词汇应用
    'userApp',                       # 添加用户管理
    'practiceApp',                   # 添加练习功能
]

SIMPLEUI_DEFAULT_THEME = 'element.css'
# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_STATIC_OFFLINE = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'funchinese.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']    # 模板文件路径
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': ['django.templatetags.static'],
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'funchinese.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': get_env('DB_HOST', '127.0.0.1'),
        'PORT': int(get_env('DB_PORT', '3306')),
        'NAME': get_env('DB_NAME', 'FunChinese'),
        'USER': get_env('DB_USER', 'root'),
        'PASSWORD': get_env('DB_PASSWORD', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'    # 静态文件前缀
# 静态文件目录列表
STATICFILES_DIRS = BASE_DIR, 'static'


MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'



# 用户认证系统使用下面自定义的用户模型
AUTH_USER_MODEL = 'userApp.UserInfo'

# 阿里云百炼配置（用于配置语音合成大模型）
DASHSCOPE_API_KEY = get_env('DASHSCOPE_API_KEY', '')
if not DASHSCOPE_API_KEY:
    warn_missing('DASHSCOPE_API_KEY')
DASHSCOPE_BASE_URL = get_env('DASHSCOPE_BASE_URL', 'https://dashscope.aliyuncs.com/api/v1')  # 服务端点
QWEN3_TTS_MODEL = get_env('QWEN3_TTS_MODEL', 'qwen3-tts-flash')            # 默认模型
QWEN3_TTS_INSTRUCT_MODEL = get_env('QWEN3_TTS_INSTRUCT_MODEL', 'qwen3-tts-instruct-flash')  # 指令控制模型（用于情绪等）


# 腾讯云智聆口语评测（SOE）
# 在 https://console.cloud.tencent.com/soe 开通服务获取
# 参数文档参考: https://cloud.tencent.com/document/product/884
TENCENT_SOE_SECRET_ID = get_env('TENCENT_SOE_SECRET_ID', '')
TENCENT_SOE_SECRET_KEY = get_env('TENCENT_SOE_SECRET_KEY', '')
TENCENT_SOE_APP_ID = get_env('TENCENT_SOE_APP_ID', '')
TENCENT_SOE_REGION = get_env('TENCENT_SOE_REGION', 'ap-guangzhou')

# DeepSeek 配置（用于自动分词、语法分析、配图推荐）
DEEPSEEK_API_KEY = get_env('DEEPSEEK_API_KEY', '')
if not DEEPSEEK_API_KEY:
    warn_missing('DEEPSEEK_API_KEY')
DEEPSEEK_BASE_URL = get_env('DEEPSEEK_BASE_URL', 'https://api.deepseek.com')
DEEPSEEK_MODEL = get_env('DEEPSEEK_MODEL', 'deepseek-chat')

# Unsplash 配图搜索（https://unsplash.com/developers）
UNSPLASH_ACCESS_KEY = get_env('UNSPLASH_ACCESS_KEY', '')
if not UNSPLASH_ACCESS_KEY:
    warn_missing('UNSPLASH_ACCESS_KEY')



